Question 1

In [2]:
import numpy as np

zero_vector = np.zeros(6)

print(zero_vector)

[0. 0. 0. 0. 0. 0.]


In [3]:
one_vector = np.ones(6)

print(one_vector)

[1. 1. 1. 1. 1. 1.]


In [6]:
square_matrix = np.array([[1, 2, 3], [4, 1, 6], [5, 9, 10]])

print(square_matrix)

[[ 1  2  3]
 [ 4  1  6]
 [ 5  9 10]]


In [8]:
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
matrix = np.array([[1, 7, 2], [7, 4, 5], [2, 5, 3]])

print(matrix)

is_symmetric = np.array_equal(matrix, matrix.T)

print(f"Is the matrix symmetric: {is_symmetric}")

[[1 7 2]
 [7 4 5]
 [2 5 3]]
Is the matrix symmetric: True


Question 2

In [12]:
p = np.array([1000000, 800000, 500000])
n = np.array([3, 4, 5])

total_amount = np.dot(p, n)
print(total_amount)

8700000


Question 3

In [16]:
from sklearn.datasets import load_digits

X = load_digits().data

similarity = np.dot(X[0], X[9])
print(similarity)

all_similarities = np.dot(X, X.T)
print(all_similarities)

2807.0
[[3070. 1866. 2264. ... 2812. 3006. 2898.]
 [1866. 4209. 3432. ... 3906. 3083. 3307.]
 [2264. 3432. 4388. ... 4005. 3063. 3697.]
 ...
 [2812. 3906. 4005. ... 5092. 3729. 4598.]
 [3006. 3083. 3063. ... 3729. 4316. 3850.]
 [2898. 3307. 3697. ... 4598. 3850. 4938.]]


Question 4

In [17]:

matrix = np.array([[2, 0], [0, 1]])

inverse_matrix = np.linalg.inv(matrix)

print(inverse_matrix)

[[0.5 0. ]
 [0.  1. ]]


Question 5

In [19]:
import pandas as pd

sales = pd.read_csv('C:/Users/Deepayan/Documents/MAVERICK/SIC/sic-code/assignment1/data/TV_Sales.csv')

X = sales[['comp_price', 'income', 'price']].values.astype(float)
y = sales['sales'].values.astype(float)

A = X[:3, [0, 1, 2]]
b = y[:3]

x = np.linalg.solve(A, b)
print(x)

[ 0.02419111  0.24772096 -0.03292908]


Question 6

In [20]:
X = sales[['comp_price', 'income', 'price']].values.astype(float)
y = sales['sales'].values.astype(float)

w, residuals, rank, s = np.linalg.lstsq(X, y, rcond=None)
print(w)

[ 0.00909657  0.0224309  -0.00618304]


Question 7

In [21]:
from scipy.spatial import distance

a = np.array([5, 4, 3, 2])
b = np.array([1, 2, 5, 5])
c = np.array([4, 4, 4, 3])

euclid_ab = distance.euclidean(a, b)
euclid_bc = distance.euclidean(b, c)
euclid_ac = distance.euclidean(a, c)

print(f"Euclidean Distances - a-b: {euclid_ab:.2f}, b-c: {euclid_bc:.2f}, a-c: {euclid_ac:.2f}")

cos_ab = distance.cosine(a, b)
cos_bc = distance.cosine(b, c)
cos_ac = distance.cosine(a, c)

print(f"Cosine Distances - a-b: {cos_ab:.2f}, b-c: {cos_bc:.2f}, a-c: {cos_ac:.2f}")

Euclidean Distances - a-b: 5.74, b-c: 4.24, a-c: 1.73
Cosine Distances - a-b: 0.30, b-c: 0.16, a-c: 0.03


Question 8

In [22]:
import numpy as np

D = np.array([[2, 1],
              [1, 2]])

eigenvalues = np.linalg.eigvals(D)
print(eigenvalues)

[3.+0.j 1.+0.j]


Question 9

In [23]:
log2 = 0.69
log3 = 1.10

log12 = 2 * log2 + log3
print(log12)

2.48


Question 10

In [24]:
import numpy as np

def inverse_logistic(y):
    return np.log(y / (1 - y))

y_val = 0.8 
x_val = inverse_logistic(y_val)

print(x_val)

1.3862943611198908


Question 11

In [26]:
import sympy as sp

x, k, a, b = sp.symbols('x k a b')

f_A = x**3 - 1
diff_A = sp.diff(f_A, x)
print(diff_A)

f_B = sp.log(x**2 - 3*k)
diff_B = sp.diff(f_B, x)
print(diff_B)

f_C = sp.exp(a * x**b)
diff_C = sp.diff(f_C, x)
print(diff_C)

3*x**2
2*x/(-3*k + x**2)
a*b*x**b*exp(a*x**b)/x


Question 12

In [28]:
x, y, k, a, b = sp.symbols('x y k a b')

f_12 = sp.exp(x**2 + 2*y**2)
print("f_x:", sp.diff(f_12, x))
print("f_y:", sp.diff(f_12, y))
print("f_xx:", sp.diff(f_12, x, x))
print("f_yy:", sp.diff(f_12, y, y))
print("f_xy:", sp.diff(f_12, x, y))
print("f_yx:", sp.diff(f_12, y, x))

f_x: 2*x*exp(x**2 + 2*y**2)
f_y: 4*y*exp(x**2 + 2*y**2)
f_xx: 2*(2*x**2 + 1)*exp(x**2 + 2*y**2)
f_yy: 4*(4*y**2 + 1)*exp(x**2 + 2*y**2)
f_xy: 8*x*y*exp(x**2 + 2*y**2)
f_yx: 8*x*y*exp(x**2 + 2*y**2)


Question 13

In [29]:
f_A = x**3 - 1
diff_A = sp.diff(f_A, x)
print("A:", diff_A)

f_B = sp.log(sp.log(x**2 - 3*k))
diff_B = sp.diff(f_B, x)
print("B:", diff_B)

f_C = sp.exp(a * x**b)
diff_C = sp.diff(f_C, x)
print("C:", diff_C)

A: 3*x**2
B: 2*x/((-3*k + x**2)*log(-3*k + x**2))
C: a*b*x**b*exp(a*x**b)/x


Question 14

In [30]:
x, y = sp.symbols('x y')

f = sp.exp(x**2 + 2*y**2)

f_x = sp.diff(f, x)
f_y = sp.diff(f, y)
f_xx = sp.diff(f, x, x)
f_xy = sp.diff(f, x, y)
f_yx = sp.diff(f, y, x)
f_yy = sp.diff(f, y, y)

print("f_x =", f_x)
print("f_y =", f_y)
print("f_xx =", f_xx)
print("f_xy =", f_xy)
print("f_yx =", f_yx)
print("f_yy =", f_yy)

f_x = 2*x*exp(x**2 + 2*y**2)
f_y = 4*y*exp(x**2 + 2*y**2)
f_xx = 2*(2*x**2 + 1)*exp(x**2 + 2*y**2)
f_xy = 8*x*y*exp(x**2 + 2*y**2)
f_yx = 8*x*y*exp(x**2 + 2*y**2)
f_yy = 4*(4*y**2 + 1)*exp(x**2 + 2*y**2)
